FROM node:20-alpine3.18

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN addgroup nodeapp && adduser -S -G nodeapp nodeapp

USER nodeapp

WORKDIR /app/

COPY --chown=nodeapp package*.json ./

RUN npm install

COPY --chown=nodeapp . .

RUN npx prisma generate

EXPOSE 3001 9229

CMD ["npm", "run", "start:dev"]
