version: "3.8"

services:
    db:
        image: postgres:16.1-alpine3.19
        restart: always
        networks:
            - work
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "admin_store"
            POSTGRES_PASSWORD: "4639802"
            POSTGRES_DB: "ecommerce"
        
    online-store-backend:
        image: online-store-backend:dev
        environment:
            - DATABASE_URL=postgresql://admin_store:4639802@db:5432/ecommerce
        env_file:
            - .env
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: online-store-backend
        networks:
            - work
        volumes:
            - ./src:/app/src
        ports:
            - "3001:3001"
            - "9229:9229" # Debug port
        depends_on:
            - db
        
networks:
    work:
        driver: bridge
volumes:
    pgdata: