FROM node:20-alpine as build-step

WORKDIR /app

COPY . /app

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN yarn install --frozen-lockfile
EXPOSE 3000 9229
CMD ["yarn", "start:debug"]
